### ISSUE TITLE
Issue with other post

### ISSUE THREAD

**Issue by chamaldesilva** [mensonones/PopUpComponent#1]
Hello I followed your this tutorial,

https://dev.to/mensonones/login-com-linkedin-usando-react-native-288n

After running the code successfully load the screen. but when I clicked the "Login with Linkedln" button I got this error message. In both android and ios.
Please help me to fix this...
![IMG_7332](https://user-images.githubusercontent.com/30325568/72447570-94adb900-37db-11ea-920c-d7846ae5389a.jpg)

**Comment by mensonones** [comment]
you following exactly code of post? if not, show me the code...

**Comment by chamaldesilva** [comment]
> you following exactly code of post? if not, show me the code...

Yes! exact same code.

**Comment by mensonones** [comment]
show me your code where you stay displayImage or all the code

**Comment by mensonones** [comment]
![Captura de tela de 2020-01-15 18-55-19](https://user-images.githubusercontent.com/5387202/72474931-a0dc4b00-37c8-11ea-8910-2728cba79fef.png)

I just did it here and it worked

**Comment by mensonones** [comment]
```javascript
import React, {useState, useEffect} from 'react';
import {StyleSheet, View, Text, Image} from 'react-native';

import LinkedInModal from 'react-native-linkedin';

import axios from 'axios';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default function App() {
  const [token, setToken] = useState('');
  const [info, setInfo] = useState();
  const [loading, setLoading] = useState(true);

  const instance = axios.create({
    baseURL: 'https://api.linkedin.com/v2',
    headers: {
      Authorization: 'Bearer ' + token,
    },
  });

  async function getInfo() {
    await instance
      .get(
        '/me?projection=(id,firstName,lastName,email-address,profilePicture(displayImage~:playableStreams))',
      )
      .then(response => {
        setInfo(response.data);
        setLoading(false);
      })
      .catch(error => console.log(error));
  }

  useEffect(() => {
    getInfo();
  }, [token]);

  const renderData = info && (
    <>
      <Text>{info.firstName.localized.pt_BR}</Text>
      <Text>{info.lastName.localized.pt_BR}</Text>
      <Image
        source={{
          uri:
            info.profilePicture['displayImage~'].elements[3]['identifiers'][0][
              'identifier'
            ],
        }}
        style={{
          width: 200,
          height: 200,
          left: 'auto',
          right: 'auto',
          justifyContent: 'center',
        }}
      />
    </>
  );

  return (
    <View style={styles.container}>
      <LinkedInModal
        clientID=""
        clientSecret=""
        redirectUri="https://api.linkedin.com/v2/me"
        onSuccess={token => setToken(token.access_token)}
        onError={error => console.log(error)}
      />
      {loading && <Text>{'Loading...'}</Text>}
      {renderData}
    </View>
  );
}
```

**Comment by chamaldesilva** [comment]
> ```js
> import React, {useState, useEffect} from 'react';
> import {StyleSheet, View, Text, Image} from 'react-native';
> 
> import LinkedInModal from 'react-native-linkedin';
> 
> import axios from 'axios';
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: '#fff',
>     justifyContent: 'center',
>     alignItems: 'center',
>   },
> });
> 
> export default function App() {
>   const [token, setToken] = useState('');
>   const [info, setInfo] = useState();
>   const [loading, setLoading] = useState(true);
> 
>   const instance = axios.create({
>     baseURL: 'https://api.linkedin.com/v2',
>     headers: {
>       Authorization: 'Bearer ' + token,
>     },
>   });
> 
>   async function getInfo() {
>     await instance
>       .get(
>         '/me?projection=(id,firstName,lastName,email-address,profilePicture(displayImage~:playableStreams))',
>       )
>       .then(response => {
>         setInfo(response.data);
>         setLoading(false);
>       })
>       .catch(error => console.log(error));
>   }
> 
>   useEffect(() => {
>     getInfo();
>   }, [token]);
> 
>   const renderData = info && (
>     <>
>       <Text>{info.firstName.localized.pt_BR}</Text>
>       <Text>{info.lastName.localized.pt_BR}</Text>
>       <Image
>         source={{
>           uri:
>             info.profilePicture['displayImage~'].elements[3]['identifiers'][0][
>               'identifier'
>             ],
>         }}
>         style={{
>           width: 200,
>           height: 200,
>           left: 'auto',
>           right: 'auto',
>           justifyContent: 'center',
>         }}
>       />
>     </>
>   );
> 
>   return (
>     <View style={styles.container}>
>       <LinkedInModal
>         clientID=""
>         clientSecret=""
>         redirectUri="https://api.linkedin.com/v2/me"
>         onSuccess={token => setToken(token.access_token)}
>         onError={error => console.log(error)}
>       />
>       {loading && <Text>{'Loading...'}</Text>}
>       {renderData}
>     </View>
>   );
> }
> ```

Hi, Thank you so much. Now profile picture shows correctly. but not showing last and first names. check the attachment.
![IMG_7363](https://user-images.githubusercontent.com/30325568/72584263-6630fa80-390f-11ea-8e65-796b85e963b3.jpg)

**Comment by chamaldesilva** [comment]
Finally!!!! I solved. Thank you you're doing really good job brother!!!
Name is not displayed because of this,

<Text>{info.firstName.localized.pt_BR}</Text>
<Text>{info.lastName.localized.pt_BR}</Text>

You need to changed it as "en_US" at the end. now response is correctly got for my localization. You should need to place your own localization.
Thank you!

**Comment by mensonones** [comment]
Yes! Property name change by your location...

Good job :)

**Comment by chamaldesilva** [comment]
Hi, can you please help me with this?
I used https://github.com/xcarpentier/react-native-linkedin/ to implement my linkedin auth for my app. but I need to implement this to a button call. (I have button in my app login screen like "Sign in with LinkedIn") please can you tell me how can I do it? I hope you understand my question and Thank you!
